language: python
python: 2.7

jobs:
  include:
    - env: TOXENV=pre-commit
      python: 3.7
      script: tox
      install: pip install tox
    - stage: Create GitHub release
      python: 3.7
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install jq
      install:
        - pip install yq
        - pip install tox
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $VERSION
      script:
        - tox
        - export VERSION="$(yq -r .metadata.template_version shell-definition.yaml)"
        - mv dist/dependencies-win32.zip dist/F5.BIG-IP.Firewall.Shell.2G.offline_dependencies_win32_$VERSION.zip
        - mv dist/dependencies-linux.zip dist/F5.BIG-IP.Firewall.Shell.2G.offline_dependencies_linux_$VERSION.zip
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: "2jhOokpd4ClUepyKhJHatxtjvLm96XcKQLgmlQHEH4qZG4JYnDV9WZEMw6uPl9JQC5J/L7r2VTAPAyO4rRdkBNQBKhwwDq2eJOY+Fcvu0MRGLCfuMKPL/Ah0IHU2IwX/tv1dIs1TrnNUSmCXyqcqnPJVfploRv1pASG4MWtqBSZWlrQ0xlL1ZftLT/JaaPR1eyqKHhDQ6qKhpCF7wZbckSShX/850H1hSIs/1Gz93X/ch7CQS7hT/YsS/Kju7QEKioseWFHkLMkbeCnlBaJNtxcQ/ZB+5glPIy4xojwBzIc47xSy0IhZL+61HPfS75tb/BUT9SeIhE7XH8rhx2iXiasaYxtSs/Y6uuT0M/ZWFDwQT1KvW8ySfcnZbOM2ETP/Ek6TIyUFd2oRlUvlL1IDmmJV58oXka3bl8JyCOT19SNmLG511ghZIjyeoJemNIqT6FkfGXXx1Mkt4IOCM9beLuS8Hmd3hYBM7URsv8cWQ11r2Rg2gm8MmnkyGYTXCf9gB+7R36K8cZVfM7+nu8IZ/If7DMcY4W7eWLZuqyhORSWKR+GXMD1OZ33CVcrayL2OrTNEWPwy+sAbqyCU1LQNB4LgjNWlDJSkSiXTmqkXEyRB4yRdvA6RQ478dCjoskjNtpU1hfAJPemtaVp+obd2t7/3qHVBw9vHdr/DvuqLoQY="
        file_glob: true
        file: dist/*.zip
        name: F5 BIG-IP Firewall Shell 2G $GIT_TAG
        target_commitish: master
        on:
          branch: master
    - stage: Check version
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install jq
      install:
        - pip install yq
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! diff <(yq .metadata.template_version shell-definition.yaml) <(git show master:shell-definition.yaml > tmp.yaml && yq .metadata.template_version tmp.yaml)"

stages:
  - name: Check version
    if: branch = master AND type = pull_request
  - name: Test
  - name: Create GitHub release
    if: branch = master AND type != pull_request
